# Generated by Django 2.1.11 on 2019-10-09 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travellogApp', '0002_auto_20191008_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='travellogApp.Place'),
        ),
    ]
